name: "Deploy Infrastructure - Dev"

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-infra-dev:
    uses: ./.github/workflows/tf-plan-apply.yml
    with:
      working_dir: "infra"
      environment: "dev"
    secrets:
      ARM_CLIENT_ID_DEV: ${{ secrets.ARM_CLIENT_ID_DEV }}
      ARM_CLIENT_ID_NONPROD: ${{ secrets.ARM_CLIENT_ID_NONPROD }}
      ARM_CLIENT_ID_PROD: ${{ secrets.ARM_CLIENT_ID_PROD }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}